version: '3'
services:
  flask-api:
    build: .
    command: "python -V"
    environment: 
      - FLASK_APP=hello.py
    command: "flask run --host=0.0.0.0"
    ports:
    - "5000:5000"
    volumes: 
    - ./:/
  modelapp:
    build: .
    ports:
    - "7000:7000"